// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKW96dwJyvRfjHYNGt4cSHuvyJiljtcqg',
    appId: '1:775525108605:web:87b998fd7fff4df7d11a14',
    messagingSenderId: '775525108605',
    projectId: 'project-4bfac',
    authDomain: 'project-4bfac.firebaseapp.com',
    storageBucket: 'project-4bfac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQjm-mGDx4xxZ5_y91YmJAhJ5rmHpmqDU',
    appId: '1:775525108605:android:88937594cc3f4eb8d11a14',
    messagingSenderId: '775525108605',
    projectId: 'project-4bfac',
    storageBucket: 'project-4bfac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA599LytrUE5-MZ6Z2z52ib2fUfW123F9k',
    appId: '1:775525108605:ios:27151a2e2ba8178cd11a14',
    messagingSenderId: '775525108605',
    projectId: 'project-4bfac',
    storageBucket: 'project-4bfac.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA599LytrUE5-MZ6Z2z52ib2fUfW123F9k',
    appId: '1:775525108605:ios:27151a2e2ba8178cd11a14',
    messagingSenderId: '775525108605',
    projectId: 'project-4bfac',
    storageBucket: 'project-4bfac.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKW96dwJyvRfjHYNGt4cSHuvyJiljtcqg',
    appId: '1:775525108605:web:659184cd04da4023d11a14',
    messagingSenderId: '775525108605',
    projectId: 'project-4bfac',
    authDomain: 'project-4bfac.firebaseapp.com',
    storageBucket: 'project-4bfac.appspot.com',
  );
}
